### ISSUE TITLE
Periodic clientside crashes

### ISSUE THREAD

**Issue by NCGoldberg** [SmashingMods/Volcano-Block#91] opened 2019-08-02 21:59 UTC
I'm occasionally getting crashes, seemingly at random. I'm not sure what's causing it, so I'm attaching the crash reports from the 4 times it has happened so far.
[Volcano Block Crash Reports.zip](https://github.com/al132mc/Volcano-Block/files/3463012/Volcano.Block.Crash.Reports.zip)

**Comment by al132mc** [comment] 2019-08-06 14:42
The first three crashes are related to the calculator "info calculator" item, please don't use that  (I could have sworn I disabled it.. but maybe not). The last crash is probably from using an empty soulbook on a soulus summoner

**Comment by MasterEnderman** [comment] 2022-05-22 09:12
duplicate of #24

**Closed by MasterEnderman** 2022-05-22 09:12 UTC
Labels: duplicate
